### ISSUE TITLE
jsonrpc example fails

### ISSUE THREAD

**Issue by flyq** [actix/examples#262]
# env
* Ubuntu 18.04 server
```shell
cargo --version
cargo 1.41.0 (626f0f40e 2019-12-03)

rustc --version
rustc 1.41.0 (5e1a79984 2020-01-27)
```

# logout
```shell
curl -X POST -H "Content-Type: application/json" -d '{"jsonrpc": "2.0", "method": "ping", "params": [], "id": 1}' http://127.0.0.1:8080
curl: (52) Empty reply from server
```

```shell
Finished dev [unoptimized + debuginfo] target(s) in 1.74s                            
     Running `target/debug/jsonrpc-example`                                                 
[2020-03-01T05:09:55Z INFO  actix_server::builder] Starting 1 workers         
[2020-03-01T05:09:55Z INFO  actix_server::builder] Starting "actix-web-service-127.0.0.1:8080" service on 127.0.0.1:8080                                    
thread 'actix-rt:worker:0' panicked at 'called `Option::unwrap()` on a `None` value', /rustc/5e1a799842ba6ed4a57e91f7ab9435947482f7d8/src/libcore/macros/mod.rs:15:40        
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.                   
```

**Comment by robjtede** [comment]
Thanks for the report. Can you run it with the backtrace enabled and replace the log?

**Comment by flyq** [comment]
`RUST_BACKTRACE=1 cargo run`:

```shell
thread 'actix-rt:worker:0' panicked at 'called `Option::unwrap()` on a `None` value', /rustc/f3e1a954d2ead4e2fc197c7da7d71e6c61bad196/src/libcore/macros/mod.rs:15:40
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:84
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:61
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1025
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1426
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:65
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:50
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:193
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:210
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:471
  11: rust_begin_unwind
             at src/libstd/panicking.rs:375
  12: core::panicking::panic_fmt
             at src/libcore/panicking.rs:84
  13: core::panicking::panic
             at src/libcore/panicking.rs:51
  14: core::option::Option<T>::unwrap
             at /rustc/f3e1a954d2ead4e2fc197c7da7d71e6c61bad196/src/libcore/macros/mod.rs:15
  15: jsonrpc_example::rpc_handler::{{closure}}
             at jsonrpc/src/main.rs:32
  16: <std::future::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/f3e1a954d2ead4e2fc197c7da7d71e6c61bad196/src/libstd/future.rs:43
  17: <actix_web::handler::HandlerServiceResponse<T,R> as core::future::future::Future>::poll
             at /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-web-2.0.0/src/handler.rs:138
  18: <actix_web::handler::ExtractResponse<T,S> as core::future::future::Future>::poll
             at /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-web-2.0.0/src/handler.rs:247
  19: <actix_web::handler::ExtractResponse<T,S> as core::future::future::Future>::poll
             at /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-web-2.0.0/src/handler.rs:258
  20: <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll
             at /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.4/src/future/future/map.rs:40
  21: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/f3e1a954d2ead4e2fc197c7da7d71e6c61bad196/src/libcore/future/future.rs:119
  22: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/f3e1a954d2ead4e2fc197c7da7d71e6c61bad196/src/libcore/future/future.rs:119
  23: <futures_util::future::either::Either<A,B> as core::future::future::Future>::poll
             at /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.4/src/future/either.rs:63
  24: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/f3e1a954d2ead4e2fc197c7da7d71e6c61bad196/src/libcore/future/future.rs:119
  25: <actix_web::middleware::logger::LoggerResponse<S,B> as core::future::future::Future>::poll
             at /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-web-2.0.0/src/middleware/logger.rs:210
  26: actix_http::h1::dispatcher::InnerDispatcher<T,S,B,X,U>::poll_response
             at /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-http-1.0.1/src/h1/dispatcher.rs:390
  27: <actix_http::h1::dispatcher::Dispatcher<T,S,B,X,U> as core::future::future::Future>::poll
             at /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-http-1.0.1/src/h1/dispatcher.rs:758
  28: actix_http::service::State<T,S,B,X,U>::poll
             at /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-http-1.0.1/src/service.rs:660
  29: <actix_http::service::HttpServiceHandlerResponse<T,S,B,X,U> as core::future::future::Future>::poll
             at /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-http-1.0.1/src/service.rs:637
  30: <actix_service::and_then::AndThenServiceResponse<A,B> as core::future::future::Future>::poll
             at /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-service-1.0.5/src/and_then.rs:103
  31: std::future::poll_with_tls_context
             at /rustc/f3e1a954d2ead4e2fc197c7da7d71e6c61bad196/src/libstd/future.rs:99
  32: <actix_server::service::StreamService<T> as actix_service::Service>::call::{{closure}}
             at /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-server-1.0.2/src/service.rs:85
  33: <std::future::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/f3e1a954d2ead4e2fc197c7da7d71e6c61bad196/src/libstd/future.rs:43
  34: tokio::task::core::Core<T>::poll
             at /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.13/src/task/core.rs:128
  35: tokio::task::harness::Harness<T,S>::poll::{{closure}}::{{closure}}
             at /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.13/src/task/harness.rs:119
  36: core::ops::function::FnOnce::call_once
             at /rustc/f3e1a954d2ead4e2fc197c7da7d71e6c61bad196/src/libcore/ops/function.rs:232
  37: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/f3e1a954d2ead4e2fc197c7da7d71e6c61bad196/src/libstd/panic.rs:318
  38: std::panicking::try::do_call
             at /rustc/f3e1a954d2ead4e2fc197c7da7d71e6c61bad196/src/libstd/panicking.rs:292
  39: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:78
  40: std::panicking::try
             at /rustc/f3e1a954d2ead4e2fc197c7da7d71e6c61bad196/src/libstd/panicking.rs:270
  41: std::panic::catch_unwind
             at /rustc/f3e1a954d2ead4e2fc197c7da7d71e6c61bad196/src/libstd/panic.rs:394
  42: tokio::task::harness::Harness<T,S>::poll::{{closure}}
             at /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.13/src/task/harness.rs:100
  43: tokio::loom::std::causal_cell::CausalCell<T>::with_mut
             at /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.13/src/loom/std/causal_cell.rs:41
  44: tokio::task::harness::Harness<T,S>::poll
             at /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.13/src/task/harness.rs:99
  45: tokio::task::raw::poll
             at /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.13/src/task/raw.rs:162
  46: tokio::task::raw::RawTask::poll
             at /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.13/src/task/raw.rs:113
  47: tokio::task::Task<S>::run
             at /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.13/src/task/mod.rs:381
  48: tokio::task::local::Scheduler::tick
             at /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.13/src/task/local.rs:513
  49: <tokio::task::local::LocalFuture<F> as core::future::future::Future>::poll::{{closure}}
             at /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.13/src/task/local.rs:407
  50: tokio::task::local::Scheduler::with::{{closure}}
             at /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.13/src/task/local.rs:478
  51: std::thread::local::LocalKey<T>::try_with
             at /rustc/f3e1a954d2ead4e2fc197c7da7d71e6c61bad196/src/libstd/thread/local.rs:262
  52: std::thread::local::LocalKey<T>::with
             at /rustc/f3e1a954d2ead4e2fc197c7da7d71e6c61bad196/src/libstd/thread/local.rs:239
  53: tokio::task::local::Scheduler::with
             at /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.13/src/task/local.rs:474
  54: <tokio::task::local::LocalFuture<F> as core::future::future::Future>::poll
             at /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.13/src/task/local.rs:402
  55: std::future::poll_with_tls_context
             at /rustc/f3e1a954d2ead4e2fc197c7da7d71e6c61bad196/src/libstd/future.rs:99
  56: tokio::task::local::LocalSet::run_until::{{closure}}
             at /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.13/src/task/local.rs:358
  57: <std::future::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/f3e1a954d2ead4e2fc197c7da7d71e6c61bad196/src/libstd/future.rs:43
  58: tokio::runtime::basic_scheduler::BasicScheduler<P>::block_on
             at /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.13/src/runtime/basic_scheduler.rs:138
  59: tokio::runtime::Runtime::block_on::{{closure}}
             at /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.13/src/runtime/mod.rs:413
  60: tokio::runtime::context::enter
             at /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.13/src/runtime/context.rs:72
  61: tokio::runtime::handle::Handle::enter
             at /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.13/src/runtime/handle.rs:34
  62: tokio::runtime::Runtime::block_on
             at /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.13/src/runtime/mod.rs:410
  63: tokio::task::local::LocalSet::block_on
             at /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.13/src/task/local.rs:321
  64: actix_rt::runtime::Runtime::block_on
             at /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-rt-1.0.0/src/runtime.rs:89
  65: actix_rt::arbiter::Arbiter::new::{{closure}}
             at /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-rt-1.0.0/src/arbiter.rs:125
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```


`RUST_BACKTRACE=full cargon run`:
```shell
     Finished dev [unoptimized + debuginfo] target(s) in 0.12s
     Running `/home/ubuntu/workspace/examples/target/debug/jsonrpc-example`
[2020-03-02T06:13:21Z INFO  actix_server::builder] Starting 4 workers
[2020-03-02T06:13:21Z INFO  actix_server::builder] Starting "actix-web-service-127.0.0.1:8080" service on 127.0.0.1:8080
thread 'actix-rt:worker:0' panicked at 'called `Option::unwrap()` on a `None` value', /rustc/f3e1a954d2ead4e2fc197c7da7d71e6c61bad196/src/libcore/macros/mod.rs:15:40
stack backtrace:
   0:     0x55f5044c8944 - backtrace::backtrace::libunwind::trace::he25250f78ba1020d
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/libunwind.rs:88
   1:     0x55f5044c8944 - backtrace::backtrace::trace_unsynchronized::hd7e25f35da233a1e
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/mod.rs:66
   2:     0x55f5044c8944 - std::sys_common::backtrace::_print_fmt::h5578a566a4c2ae4e
                               at src/libstd/sys_common/backtrace.rs:84
   3:     0x55f5044c8944 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hd4f87054ec86e936
                               at src/libstd/sys_common/backtrace.rs:61
   4:     0x55f5044e97dc - core::fmt::write::h393d55821fa8e2cb
                               at src/libcore/fmt/mod.rs:1025
   5:     0x55f5044c4577 - std::io::Write::write_fmt::hc6645302c23e4504
                               at src/libstd/io/mod.rs:1426
   6:     0x55f5044caa9e - std::sys_common::backtrace::_print::he8a0a3ebec70e1d6
                               at src/libstd/sys_common/backtrace.rs:65
   7:     0x55f5044caa9e - std::sys_common::backtrace::print::hc2635fd6c7743ade
                               at src/libstd/sys_common/backtrace.rs:50
   8:     0x55f5044caa9e - std::panicking::default_hook::{{closure}}::h9849388798b72b2b
                               at src/libstd/panicking.rs:193
   9:     0x55f5044ca791 - std::panicking::default_hook::h66e3afff11b02e47
                               at src/libstd/panicking.rs:210
  10:     0x55f5044cb17b - std::panicking::rust_panic_with_hook::hf6d05969fcffff03
                               at src/libstd/panicking.rs:471
  11:     0x55f5044cad2e - rust_begin_unwind
                               at src/libstd/panicking.rs:375
  12:     0x55f5044e61ae - core::panicking::panic_fmt::he794217b0df3f806
                               at src/libcore/panicking.rs:84
  13:     0x55f5044e60fa - core::panicking::panic::h104b3bcaeb5f1ff0
                               at src/libcore/panicking.rs:51
  14:     0x55f503e3b6af - core::option::Option<T>::unwrap::hb38d489360637462
                               at /rustc/f3e1a954d2ead4e2fc197c7da7d71e6c61bad196/src/libcore/macros/mod.rs:15
  15:     0x55f503dab73d - jsonrpc_example::rpc_handler::{{closure}}::hbfac4a54340258a1
                               at jsonrpc/src/main.rs:32
  16:     0x55f503e127d8 - <std::future::GenFuture<T> as core::future::future::Future>::poll::hb79342667cd4e66e
                               at /rustc/f3e1a954d2ead4e2fc197c7da7d71e6c61bad196/src/libstd/future.rs:43
  17:     0x55f503dd99c6 - <actix_web::handler::HandlerServiceResponse<T,R> as core::future::future::Future>::poll::h8809f7b5ca0c258a
                               at /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-web-2.0.0/src/handler.rs:138
  18:     0x55f503ddaa45 - <actix_web::handler::ExtractResponse<T,S> as core::future::future::Future>::poll::ha15b0282aa84e0d3
                               at /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-web-2.0.0/src/handler.rs:247
  19:     0x55f503ddafcc - <actix_web::handler::ExtractResponse<T,S> as core::future::future::Future>::poll::ha15b0282aa84e0d3
                               at /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-web-2.0.0/src/handler.rs:258
  20:     0x55f503dcb951 - <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll::h3c6f6b7b03e53323
                               at /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.4/src/future/future/map.rs:40
  21:     0x55f503e96ab1 - <core::pin::Pin<P> as core::future::future::Future>::poll::h0f81c806aa7e5ba8
                               at /rustc/f3e1a954d2ead4e2fc197c7da7d71e6c61bad196/src/libcore/future/future.rs:119
  22:     0x55f503e96ab1 - <core::pin::Pin<P> as core::future::future::Future>::poll::h0f81c806aa7e5ba8
                               at /rustc/f3e1a954d2ead4e2fc197c7da7d71e6c61bad196/src/libcore/future/future.rs:119
  23:     0x55f503ec85ba - <futures_util::future::either::Either<A,B> as core::future::future::Future>::poll::h07fb658f26c6f510
                               at /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.4/src/future/either.rs:63
  24:     0x55f503e96ab1 - <core::pin::Pin<P> as core::future::future::Future>::poll::h0f81c806aa7e5ba8
                               at /rustc/f3e1a954d2ead4e2fc197c7da7d71e6c61bad196/src/libcore/future/future.rs:119
  25:     0x55f503db4ae9 - <actix_web::middleware::logger::LoggerResponse<S,B> as core::future::future::Future>::poll::hf57fd17c2309c622
                               at /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-web-2.0.0/src/middleware/logger.rs:210
  26:     0x55f503da012d - actix_http::h1::dispatcher::InnerDispatcher<T,S,B,X,U>::poll_response::h1fe6b2d0340a60a1
                               at /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-http-1.0.1/src/h1/dispatcher.rs:390
  27:     0x55f503da5673 - <actix_http::h1::dispatcher::Dispatcher<T,S,B,X,U> as core::future::future::Future>::poll::h39d2925e547aca6a
                               at /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-http-1.0.1/src/h1/dispatcher.rs:758
  28:     0x55f503df633e - actix_http::service::State<T,S,B,X,U>::poll::h7e5c85998d2bfd2f
                               at /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-http-1.0.1/src/service.rs:660
  29:     0x55f503df8a7f - <actix_http::service::HttpServiceHandlerResponse<T,S,B,X,U> as core::future::future::Future>::poll::he0534eb8c631d963
                               at /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-http-1.0.1/src/service.rs:637
  30:     0x55f503daebee - <actix_service::and_then::AndThenServiceResponse<A,B> as core::future::future::Future>::poll::h930aca8adc3fe808
                               at /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-service-1.0.5/src/and_then.rs:103
  31:     0x55f503e11aba - std::future::poll_with_tls_context::h17be901a9aee273f
                               at /rustc/f3e1a954d2ead4e2fc197c7da7d71e6c61bad196/src/libstd/future.rs:99
  32:     0x55f503dcb697 - <actix_server::service::StreamService<T> as actix_service::Service>::call::{{closure}}::hf7b17880f0ce1729
                               at /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-server-1.0.2/src/service.rs:85
  33:     0x55f503e1203a - <std::future::GenFuture<T> as core::future::future::Future>::poll::h03e8d611f8185a48
                               at /rustc/f3e1a954d2ead4e2fc197c7da7d71e6c61bad196/src/libstd/future.rs:43
  34:     0x55f503e37d59 - tokio::task::core::Core<T>::poll::h918fb66b91bbf879
                               at /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.13/src/task/core.rs:128
  35:     0x55f503e16b14 - tokio::task::harness::Harness<T,S>::poll::{{closure}}::{{closure}}::he30c4fe4ba21a87e
                               at /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.13/src/task/harness.rs:119
  36:     0x55f503ddee48 - core::ops::function::FnOnce::call_once::h8de906d3c12d2c61
                               at /rustc/f3e1a954d2ead4e2fc197c7da7d71e6c61bad196/src/libcore/ops/function.rs:232
  37:     0x55f503dbd1fd - <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::h40257a349d52fd20
                               at /rustc/f3e1a954d2ead4e2fc197c7da7d71e6c61bad196/src/libstd/panic.rs:318
  38:     0x55f503df9560 - std::panicking::try::do_call::hdfd9038140b21e14
                               at /rustc/f3e1a954d2ead4e2fc197c7da7d71e6c61bad196/src/libstd/panicking.rs:292
  39:     0x55f5044cf3ba - __rust_maybe_catch_panic
                               at src/libpanic_unwind/lib.rs:78
  40:     0x55f503df9367 - std::panicking::try::habc73b371f07ddcb
                               at /rustc/f3e1a954d2ead4e2fc197c7da7d71e6c61bad196/src/libstd/panicking.rs:270
  41:     0x55f503dbd334 - std::panic::catch_unwind::hd08eb9df956a5f42
                               at /rustc/f3e1a954d2ead4e2fc197c7da7d71e6c61bad196/src/libstd/panic.rs:394
  42:     0x55f503e16a42 - tokio::task::harness::Harness<T,S>::poll::{{closure}}::hbd42c4dbd312b869
                               at /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.13/src/task/harness.rs:100
  43:     0x55f503e1374f - tokio::loom::std::causal_cell::CausalCell<T>::with_mut::h54cb493a3b6a43cd
                               at /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.13/src/loom/std/causal_cell.rs:41
  44:     0x55f503e16603 - tokio::task::harness::Harness<T,S>::poll::h5aedee19457d1b2a
                               at /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.13/src/task/harness.rs:99
  45:     0x55f503df4186 - tokio::task::raw::poll::hfba15fa4c1316e5e
                               at /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.13/src/task/raw.rs:162
  46:     0x55f5044514b7 - tokio::task::raw::RawTask::poll::h24fbdd9b586a1fc5
                               at /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.13/src/task/raw.rs:113
  47:     0x55f504452f0c - tokio::task::Task<S>::run::h0780a02b7972b561
                               at /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.13/src/task/mod.rs:381
  48:     0x55f504462f7b - tokio::task::local::Scheduler::tick::h7291c3814d658cd7
                               at /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.13/src/task/local.rs:513
  49:     0x55f5043a2a68 - <tokio::task::local::LocalFuture<F> as core::future::future::Future>::poll::{{closure}}::h4f678193af49b3ad
                               at /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.13/src/task/local.rs:407
  50:     0x55f5043a2437 - tokio::task::local::Scheduler::with::{{closure}}::h1617b0eba480b464
                               at /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.13/src/task/local.rs:478
  51:     0x55f5043cdd8a - std::thread::local::LocalKey<T>::try_with::h54b31e5be0b6f9f8
                               at /rustc/f3e1a954d2ead4e2fc197c7da7d71e6c61bad196/src/libstd/thread/local.rs:262
  52:     0x55f5043ccbec - std::thread::local::LocalKey<T>::with::h77717c1587439dbe
                               at /rustc/f3e1a954d2ead4e2fc197c7da7d71e6c61bad196/src/libstd/thread/local.rs:239
  53:     0x55f5043a22ef - tokio::task::local::Scheduler::with::h5e42b48181faa100
                               at /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.13/src/task/local.rs:474
  54:     0x55f5043a2940 - <tokio::task::local::LocalFuture<F> as core::future::future::Future>::poll::hc728b35bdf428e59
                               at /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.13/src/task/local.rs:402
  55:     0x55f5043a2e70 - std::future::poll_with_tls_context::hd383cabfcd6e19ee
                               at /rustc/f3e1a954d2ead4e2fc197c7da7d71e6c61bad196/src/libstd/future.rs:99
  56:     0x55f5043a211e - tokio::task::local::LocalSet::run_until::{{closure}}::h779be99e3ded81c0
                               at /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.13/src/task/local.rs:358
  57:     0x55f5043a752f - <std::future::GenFuture<T> as core::future::future::Future>::poll::h20b50b5d6557da06
                               at /rustc/f3e1a954d2ead4e2fc197c7da7d71e6c61bad196/src/libstd/future.rs:43
  58:     0x55f5043bfb50 - tokio::runtime::basic_scheduler::BasicScheduler<P>::block_on::hd869b61e53d115db
                               at /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.13/src/runtime/basic_scheduler.rs:138
  59:     0x55f5043b30fb - tokio::runtime::Runtime::block_on::{{closure}}::hc0471905049eec0a
                               at /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.13/src/runtime/mod.rs:413
  60:     0x55f5043a6674 - tokio::runtime::context::enter::hdd455947407fa9d0
                               at /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.13/src/runtime/context.rs:72
  61:     0x55f5043a64af - tokio::runtime::handle::Handle::enter::h97652057b56c251e
                               at /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.13/src/runtime/handle.rs:34
  62:     0x55f5043b2f6e - tokio::runtime::Runtime::block_on::hfe06ade1c3b124c0
                               at /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.13/src/runtime/mod.rs:410
  63:     0x55f5043a1ca5 - tokio::task::local::LocalSet::block_on::h22eca203f0dc6cc9
                               at /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.13/src/task/local.rs:321
  64:     0x55f504397ec8 - actix_rt::runtime::Runtime::block_on::hbd7b1727f78cdbf5
                               at /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-rt-1.0.0/src/runtime.rs:89
  65:     0x55f5043991a8 - actix_rt::arbiter::Arbiter::new::{{closure}}::h051fb5d6f4b009ba
                               at /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-rt-1.0.0/src/arbiter.rs:125
  66:     0x55f5043a2c40 - std::sys_common::backtrace::__rust_begin_short_backtrace::hdfaa3624028ee29e
                               at /rustc/f3e1a954d2ead4e2fc197c7da7d71e6c61bad196/src/libstd/sys_common/backtrace.rs:136
  67:     0x55f5043bb4e1 - std::thread::Builder::spawn_unchecked::{{closure}}::{{closure}}::h542e8ba0a8011504
                               at /rustc/f3e1a954d2ead4e2fc197c7da7d71e6c61bad196/src/libstd/thread/mod.rs:469
  68:     0x55f5043a7bf3 - <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::hf6668c51e836e958
                               at /rustc/f3e1a954d2ead4e2fc197c7da7d71e6c61bad196/src/libstd/panic.rs:318
  69:     0x55f5043b5683 - std::panicking::try::do_call::h490ed5ca5e7f2dbf
                               at /rustc/f3e1a954d2ead4e2fc197c7da7d71e6c61bad196/src/libstd/panicking.rs:292
  70:     0x55f5044cf3ba - __rust_maybe_catch_panic
                               at src/libpanic_unwind/lib.rs:78
  71:     0x55f5043b4ba8 - std::panicking::try::h26e003ceafcee53b
                               at /rustc/f3e1a954d2ead4e2fc197c7da7d71e6c61bad196/src/libstd/panicking.rs:270
  72:     0x55f5043a7c63 - std::panic::catch_unwind::h2c99a8304d5e6813
                               at /rustc/f3e1a954d2ead4e2fc197c7da7d71e6c61bad196/src/libstd/panic.rs:394
  73:     0x55f5043bb2c6 - std::thread::Builder::spawn_unchecked::{{closure}}::hbf317c7c2d456d81
                               at /rustc/f3e1a954d2ead4e2fc197c7da7d71e6c61bad196/src/libstd/thread/mod.rs:468
  74:     0x55f50439bc84 - core::ops::function::FnOnce::call_once{{vtable.shim}}::h6c22156538de7421
                               at /rustc/f3e1a954d2ead4e2fc197c7da7d71e6c61bad196/src/libcore/ops/function.rs:232
  75:     0x55f5044bf16f - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::he56d3c54b825d402
                               at /rustc/f3e1a954d2ead4e2fc197c7da7d71e6c61bad196/src/liballoc/boxed.rs:1022
  76:     0x55f5044ce7e0 - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::h77a97c96311f0af9
                               at /rustc/f3e1a954d2ead4e2fc197c7da7d71e6c61bad196/src/liballoc/boxed.rs:1022
  77:     0x55f5044ce7e0 - std::sys_common::thread::start_thread::hc7f86820e887a527
                               at src/libstd/sys_common/thread.rs:13
  78:     0x55f5044ce7e0 - std::sys::unix::thread::Thread::new::thread_start::h2fc884c15f11e4da
                               at src/libstd/sys/unix/thread.rs:80
  79:     0x7fe91f76b6db - start_thread
  80:     0x7fe91f27c88f - __clone
  81:                0x0 - <unknown>

```

**Comment by robjtede** [comment]
Eyeballing it: `jsonrpc/src/main.rs:32` is extracting the `HttpRequest::app_data` and T is probably inferred as AppState given it's passed into a function using that type. However, since it's set using `App::data` then T is wrong; it should be Data<AppState>. It will need an explicit T on the app_data call or using the Data extractor in the handler signature.
